name: Docker deploy 2

on:
  push:
    branches:
      - hw6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login (Yandex Cloud)
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.AUTHORIZED_KEY }}

      - name: Build image (Yandex Cloud)
        env:
          CR_REGISTRY: crp7qfv6r081t2ofp03o
          CR_REPOSITORY: backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:user$IMAGE_TAG ./homeworks/K33412/Tanachev\ Egor/HW6/task/user
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:user$IMAGE_TAG
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:market$IMAGE_TAG ./homeworks/K33412/Tanachev\ Egor/HW6/task/market
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:market$IMAGE_TAG
        

      - name: Connect to VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 51.250.111.202
          username: admin
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22

      - name: Run commands on VM
        env:
           YANDEX_KEY: ${{ secrets.YANDEX_KEY }}
           IMAGE_TAG: ${{ github.sha }}
        run: |
          sudo docker login --username oauth --password $YANDEX_KEY cr.yandex
          if [ "$(docker ps -q)" ]; then
            sudo docker kill $(docker ps -q) &> /dev/null
          fi
          if [ "$(docker ps -a -q)" ]; then
            sudo docker rm $(docker ps -a -q) &> /dev/null
          fi
          sudo docker run -dp 80:1111 cr.yandex/crp7qfv6r081t2ofp03o/backend:user${{ github.sha }} && sudo docker run -dp 81:2222 cr.yandex/crp7qfv6r081t2ofp03o/backend:market${{ github.sha }}