PROJECT = "lr-2"

all: install server-nodemon

server-nodemon: 
	@echo "Starting ${PROJECT}....."
	npm run nodemon

server: 
	@echo "Starting ${PROJECT}....."
	npm run start

install: 
	@echo "Installing ${PROJECT}....."
	npm install

.PHONY: server install clean update all