init:
	npm i

build:
	npm run build

migrate:
	npm run migrate

run:
	npm start

lint:
	npm run lint

style-check:
	npx prettier --check .

style-fix:
	npx prettier --write .

.PHONY: init build migrate run lint style-check style-fix
.DEFAULT_GOAL: init
