.PHONY: dev
dev:
	yarn prisma migrate dev --name init
	yarn run dev

.PHONE: build
build:
	yarn run build

.PHONE: start
start:
	yarn prisma migrate dev --name init
	yarn run start

.PHONE: init
init:
	yarn init