.PHONY: init
init:
	npm install

.PHONY: prestart
prestart:
	npm run prestart

.PHONY: start
start:
	npm run start

.PHONY: start_prod
start_prod:
	npm run start:prod

.PHONY: migrate
migrate:
	npm run migrate --name=$(name)

.DEFAULT_GOAL: init